service: agenda-med
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-esbuild

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
