AppointmentTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AppointmentTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: provider_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: dateIndex
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: providerIdIndex
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: userIdIndex
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
