ServiceTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ServiceTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: provider_id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: providerIdIndex
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
