ScheduleTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ScheduleTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: doctor_id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: dateIndex
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: doctorIdIndex
        KeySchema:
          - AttributeName: doctor_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
