UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UsersTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: latitude
        AttributeType: N
      - AttributeName: longitude
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: latitudeLongitudeIndex
        KeySchema:
          - AttributeName: latitude
            KeyType: HASH
          - AttributeName: longitude
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
