AppointmentTableIAM:
  Effect: Allow
  Action:
    - dynamodb:PutItem
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:UpdateItem
    - dynamodb:Query
  Resource:
    - ${self:custom.AppointmentTable.arn}
    - !Join ['/', ['${self:custom.AppointmentTable.arn}', 'index', 'dateIndex']]
    - !Join [
        '/',
        ['${self:custom.AppointmentTable.arn}', 'index', 'providerIdIndex'],
      ]
    - !Join [
        '/',
        ['${self:custom.AppointmentTable.arn}', 'index', 'userIdIndex'],
      ]
